version: '2.2'
services:
  geoserver-slave:
    image: gs_unavco:latest
    build:
      context: .
      args:
        GEOSERVER_WEBAPP_SRC: geoserver.war
    restart: always
    environment:
      - JAVA_OPTS=-Xms${MEM} -Xmx${MEM} -XX:+UseParallelGC -XX:+UseParallelOldGC -DGEOWEBCACHE_CONFIG_DIR=$${GEOSERVER_DATA_DIR}/gwc -DGEOSERVER_LOG_LOCATION=$${GEOSERVER_HOME}/logs/$${HOSTNAME}-slave.log -DGEOSERVER_NODE_OPTS=id:slave-$${HOSTNAME} -DGEOSERVER_AUDIT_PATH=/var/geoserver/audits/geoserver-${DOCKER_HOSTNAME}-slave-$${HOSTNAME}
      # uncomment next line if you want to enable sticky session (so it's possible to access geoserver admin panel on each slave)
      # - COOKIE=JSESSIONID prefix
    volumes:
      - geoserver_slaves_datadir:/var/geoserver/datadir:rw
      - geoserver_slaves_gwccachedir:/var/geoserver/gwc_cache_dir:rw
      - shared_data:/var/geoserver/data:rw
      - shared_logs:/var/geoserver/logs:rw
      - shared_audits:/var/geoserver/audits:rw
      - ./config/context.xml:/usr/local/tomcat/conf/context.xml:ro

  geoserver-master:
    image: gs_unavco:latest
    restart: always
    ports:
      - '8080:8080'
    environment:
      - GEOSERVER_APP_NAME=master
      - JAVA_OPTS=-Xms${MEM} -Xmx${MEM} -XX:+UseParallelGC -XX:+UseParallelOldGC -DGEOWEBCACHE_CONFIG_DIR=$${GEOSERVER_DATA_DIR}/gwc -DGEOSERVER_LOG_LOCATION=$${GEOSERVER_HOME}/logs/$${HOSTNAME}-master.log -DGEOSERVER_NODE_OPTS=id:master-$${HOSTNAME} -DGEOSERVER_AUDIT_PATH=/var/geoserver/audits/geoserver-${DOCKER_HOSTNAME}-master-$${HOSTNAME}
    volumes:
      - geoserver_master_datadir:/var/geoserver/datadir:rw
      - geoserver_master_gwccachedir:/var/geoserver/gwc_cache_dir:rw
      - shared_data:/var/geoserver/data:rw
      - shared_logs:/var/geoserver/logs:rw
      - shared_audits:/var/geoserver/audits:rw
      - ./config/context.xml:/usr/local/tomcat/conf/context.xml:ro

  haproxy:
    image: dockercloud/haproxy
    container_name: haproxy
    depends_on:
      - geoserver-slave
    links:
      - geoserver-slave
    ports:
      # geoserver instances are behind haproxy (which is mapped on host at port 80)
      - '80:80'
      # uncomment next line if you want to see haproxy admin panel (allows to list proxied geoserver slave instances)
      #- '1936:1936'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    # uncomment this enviroment section if you want to access haproxy admin panel (with credentials admin:admin)
    #environment:
    #  - 'STATS_AUTH="admin:admin"'

volumes:
  geoserver_slaves_datadir:
    external: true
    name: geoserver_slaves_datadir
  geoserver_slaves_gwccachedir:
    external: true
    name: geoserver_slaves_gwccachedir
  geoserver_master_datadir:
    external: true
    name: geoserver_master_datadir
  geoserver_master_gwccachedir:
    external: true
    name: geoserver_master_gwccachedir
  shared_data:
    external: true
    name: shared_data
  shared_logs:
    external: true
    name: shared_logs
  shared_audits:
    external: true
    name: shared_audits