version: '3'
services:

  geoserver:
    image: geosolutionsit/geoserver:gs-${DOCKER_IMAGE_VERSION}
    restart: always
    ports:
      - '8001:8080'
    environment:
      - JAVA_OPTS=-Xms${MEM} -Xmx${MEM} -XX:+UseParallelGC -XX:+UseParallelOldGC -DGEOWEBCACHE_CONFIG_DIR=$${GEOSERVER_DATA_DIR}/gwc -DGEOSERVER_LOG_LOCATION=$${GEOSERVER_HOME}/logs/$${HOSTNAME}-slave.log -DGEOSERVER_NODE_OPTS=id:slave-$${HOSTNAME} -DGEOSERVER_AUDIT_PATH=/var/geoserver/audits/geoserver-${DOCKER_HOSTNAME}-slave-$${HOSTNAME}
    volumes:
      - geoserver-slaves-datadir:/var/geoserver/datadir
      - geoserver-slaves-gwccachedir:/var/geoserver/gwc_cache_dir
      - shared-data:/var/geoserver/data
      - shared-logs:/var/geoserver/logs
      - shared-audits:/var/geoserver/audits
      - ./config/context.xml:/usr/local/tomcat/conf/context.xml

  geoserver-master:
    image: geosolutionsit/geoserver:gs-${DOCKER_IMAGE_VERSION}
    restart: always
    ports:
      - '8000:8080'
    environment:
      - JAVA_OPTS=-Xms${MEM} -Xmx${MEM} -XX:+UseParallelGC -XX:+UseParallelOldGC -DGEOWEBCACHE_CONFIG_DIR=$${GEOSERVER_DATA_DIR}/gwc -DGEOSERVER_LOG_LOCATION=$${GEOSERVER_HOME}/logs/$${HOSTNAME}-master.log -DGEOSERVER_NODE_OPTS=id:master-$${HOSTNAME} -DGEOSERVER_AUDIT_PATH=/var/geoserver/audits/geoserver-${DOCKER_HOSTNAME}-master-$${HOSTNAME}
    volumes:
      - geoserver-master-datadir:/var/geoserver/datadir
      - geoserver-master-gwccachedir:/var/geoserver/gwc_cache_dir
      - shared-data:/var/geoserver/data
      - shared-logs:/var/geoserver/logs
      - shared-audits:/var/geoserver/audits
      - ./config/context.xml:/usr/local/tomcat/conf/context.xml

volumes:
  geoserver-slaves-datadir:
  geoserver-slaves-gwccachedir:
  geoserver-master-datadir:
  geoserver-master-gwccachedir:
  shared-data:
  shared-logs:
  shared-audits: