version: '3'
services:
    geoserver:
      image: geosolutionsit/geoserver:gs-${DOCKER_IMAGE_VERSION}
      restart: always
      ports:
        - '8001:8080'
      environment:
        - JAVA_OPTS=-Xms${MEM} -Xmx${MEM} -XX:+UseParallelGC -XX:+UseParallelOldGC -DGEOWEBCACHE_CONFIG_DIR=$${GEOSERVER_DATA_DIR}/gwc -DGEOSERVER_LOG_LOCATION=$${GEOSERVER_HOME}/logs/$${HOSTNAME}-slave.log -DGEOSERVER_NODE_OPTS=id:slave-$${HOSTNAME} -DGEOSERVER_AUDIT_PATH=/var/geoserver/audits/geoserver-${DOCKER_HOSTNAME}-slave-$${HOSTNAME}
      volumes:
        - './volumes/geoserver-slaves/data_dir/:/var/geoserver/datadir'
        - './volumes/geoserver-slaves/gwc_cache_dir/:/var/geoserver/gwc_cache_dir'
        - './volumes/shared/data/:/var/geoserver/data'
        - './volumes/shared/logs/:/var/geoserver/logs'
        - './volumes/shared/audits/:/var/geoserver/audits'
        - './config/context.xml:/usr/local/tomcat/conf/context.xml'
      depends_on:
        - postgresql

    geoserver-master:
      image: geosolutionsit/geoserver:gs-${DOCKER_IMAGE_VERSION}
      restart: always
      ports:
        - '8000:8080'
      environment:
        - JAVA_OPTS=-Xms${MEM} -Xmx${MEM} -XX:+UseParallelGC -XX:+UseParallelOldGC -DGEOWEBCACHE_CONFIG_DIR=$${GEOSERVER_DATA_DIR}/gwc -DGEOSERVER_LOG_LOCATION=$${GEOSERVER_HOME}/logs/$${HOSTNAME}-master.log -DGEOSERVER_NODE_OPTS=id:master-$${HOSTNAME} -DGEOSERVER_AUDIT_PATH=/var/geoserver/audits/geoserver-${DOCKER_HOSTNAME}-master-$${HOSTNAME}
      volumes:
        - './volumes/geoserver-master/data_dir/:/var/geoserver/datadir'
        - './volumes/geoserver-master/gwc_cache_dir/:/var/geoserver/gwc_cache_dir'
        - './volumes/shared/data/:/var/geoserver/data'
        - './volumes/shared/logs/:/var/geoserver/logs'
        - './volumes/shared/audits/:/var/geoserver/audits'
        - './config/context.xml:/usr/local/tomcat/conf/context.xml'
      depends_on:
        - postgresql

    # used for testing purposes
    postgresql:
      image: 'kartoza/postgis:9.6-2.4'
      hostname: postgresql
      env_file:
        - ./config/postgis.env
      ports:
        - '5432:5432'
      volumes:
        - './volumes/pg/postgis-data:/var/lib/postgresql'
      restart: on-failure
      healthcheck:
        test: "exit 0"

    # used for testing purposes
    pgadmin:
      image: 'dpage/pgadmin4'
      environment:
        - PGADMIN_LISTEN_PORT=80
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=1234
      volumes:
        - './config/pgadmin/servers.json:/pgadmin4/servers.json'
      ports:
        - '81:80'

